-- UI
local v466 = loadstring(game:HttpGet("https://raw.githubusercontent.com/Rizeniii/diamond/refs/heads/main/ch.lua"))():MakeWindow({
    Title = "Diamond Hub",
    SubTitle = "",
    SaveFolder = "dex.lua"
})
local l_ScreenGui_0 = Instance.new("ScreenGui")
l_ScreenGui_0.Name = "ControlGUI"
l_ScreenGui_0.Parent = game.CoreGui
local l_ImageButton_0 = Instance.new("ImageButton")
l_ImageButton_0.Size = UDim2.new(0, 50, 0, 50)
l_ImageButton_0.Position = UDim2.new(0.15, 0, 0.15, 0)
l_ImageButton_0.Image = "rbxassetid://122340386055007"
l_ImageButton_0.BackgroundTransparency = 1
l_ImageButton_0.Parent = l_ScreenGui_0
local l_UICorner_0 = Instance.new("UICorner")
l_UICorner_0.CornerRadius = UDim.new(0.25, 0)
l_UICorner_0.Parent = l_ImageButton_0
local l_UIStroke_0 = Instance.new("UIStroke")
l_UIStroke_0.Thickness = 2
l_UIStroke_0.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
l_UIStroke_0.Parent = l_ImageButton_0
local v471 = {
    Color3.fromRGB(0, 0, 0),
    Color3.fromRGB(0, 0, 0),
    Color3.fromRGB(0, 0, 0),
    Color3.fromRGB(0, 0, 0),
    Color3.fromRGB(0, 00, 0),
    Color3.fromRGB(0, 0, 0),
    Color3.fromRGB(0, 0, 0)
}
task.spawn(function()
    local v472 = 1
    while true do
        l_UIStroke_0.Color = v471[v472]
        v472 = v472 % #v471 + 1
        task.wait(0.3)
    end
end)
local v473 = true
local v474 = nil
local v475 = nil
local v476 = nil
local v477 = nil
local function v480(v478)
    local v479 = v478.Position - v476
    l_ImageButton_0.Position = UDim2.new(v477.X.Scale, v477.X.Offset + v479.X, v477.Y.Scale, v477.Y.Offset + v479.Y)
end
l_ImageButton_0.InputBegan:Connect(function(v481)
    if v481.UserInputType == Enum.UserInputType.Touch or v481.UserInputType == Enum.UserInputType.MouseButton1 then
        v474 = true
        v476 = v481.Position
        v477 = l_ImageButton_0.Position
        v481.Changed:Connect(function()
            if v481.UserInputState == Enum.UserInputState.End then
                v474 = false
            end
        end)
    end
end)
l_ImageButton_0.InputChanged:Connect(function(v482)
    if v482.UserInputType == Enum.UserInputType.Touch or v482.UserInputType == Enum.UserInputType.MouseMovement then
        v475 = v482
    end
end)
game:GetService("UserInputService").InputChanged:Connect(function(v483)
    if v474 and v483 == v475 then
        v480(v483)
    end
end)
l_ImageButton_0.MouseButton1Click:Connect(function()
    v473 = not v473
    if v473 then
        v466:Minimize(false)
    else
        v466:Minimize(true)
    end
end)
-- UI

-- FUNCTIONS
QuestCheck = function()
    local a = game.Players.LocalPlayer.Data.Level.Value;
    if World1 then
        if a == 1 or a <= 9 then
            if tostring(TeamSelf) == "Marines" then
                Mon = "Trainee"
                Qname = "MarineQuest"
                Qdata = 1;
                NameMon = "Trainee"
                PosM = CFrame.new(-2709.67944, 24.5206585, 2104.24585, -0.744724929, -3.97967455e-08, -0.667371571, 4.32403588e-08, 1, -1.07884304e-07, 0.667371571, -1.09201515e-07, -0.744724929)
                PosQ = CFrame.new(-2709.67944, 24.5206585, 2104.24585, -0.744724929, -3.97967455e-08, -0.667371571, 4.32403588e-08, 1, -1.07884304e-07, 0.667371571, -1.09201515e-07, -0.744724929)
            elseif tostring(TeamSelf) == "Pirates" then
                Mon = "Bandit"
                Qdata = 1;
                Qname = "BanditQuest1"
                NameMon = "Bandit"
                PosM = CFrame.new(1045.962646484375, 27.00250816345215, 1560.8203125)
                PosQ = CFrame.new(1045.962646484375, 27.00250816345215, 1560.8203125)
            end
        elseif a == 10 or a <= 14 then
            Mon = "Monkey"
            Qdata = 1;
            Qname = "JungleQuest"
            NameMon = "Monkey"
            PosQ = CFrame.new(-1598.08911, 35.5501175, 153.377838, 0, 0, 1, 0, 1, -0, -1, 0, 0)
            PosM = CFrame.new(-1448.51806640625, 67.85301208496094, 11.46579647064209)
        elseif a == 15 or a <= 29 then
            Mon = "Gorilla"
            Qdata = 2;
            Qname = "JungleQuest"
            NameMon = "Gorilla"
            PosQ = CFrame.new(-1598.08911, 35.5501175, 153.377838, 0, 0, 1, 0, 1, -0, -1, 0, 0)
            PosM = CFrame.new(-1129.8836669921875, 40.46354675292969, -525.4237060546875)
        elseif a == 30 or a <= 39 then
            Mon = "Pirate"
            Qdata = 1;
            Qname = "BuggyQuest1"
            NameMon = "Pirate"
            PosQ = CFrame.new(-1141.07483, 4.10001802, 3831.5498, 0.965929627, -0, -0.258804798, 0, 1, -0, 0.258804798, 0, 0.965929627)
            PosM = CFrame.new(-1103.513427734375, 13.752052307128906, 3896.091064453125)
        elseif a == 40 or a <= 59 then
            Mon = "Brute"
            Qdata = 2;
            Qname = "BuggyQuest1"
            NameMon = "Brute"
            PosQ = CFrame.new(-1141.07483, 4.10001802, 3831.5498, 0.965929627, -0, -0.258804798, 0, 1, -0, 0.258804798, 0, 0.965929627)
            PosM = CFrame.new(-1140.083740234375, 14.809885025024414, 4322.92138671875)
        elseif a == 60 or a <= 74 then
            Mon = "Desert Bandit"
            Qdata = 1;
            Qname = "DesertQuest"
            NameMon = "Desert Bandit"
            PosQ = CFrame.new(894.488647, 5.14000702, 4392.43359, 0.819155693, -0, -0.573571265, 0, 1, -0, 0.573571265, 0, 0.819155693)
            PosM = CFrame.new(924.7998046875, 6.44867467880249, 4481.5859375)
        elseif a == 75 or a <= 89 then
            Mon = "Desert Officer"
            Qdata = 2;
            Qname = "DesertQuest"
            NameMon = "Desert Officer"
            PosQ = CFrame.new(894.488647, 5.14000702, 4392.43359, 0.819155693, -0, -0.573571265, 0, 1, -0, 0.573571265, 0, 0.819155693)
            PosM = CFrame.new(1608.2822265625, 8.614224433898926, 4371.00732421875)
        elseif a == 90 or a <= 99 then
            Mon = "Snow Bandit"
            Qdata = 1;
            Qname = "SnowQuest"
            NameMon = "Snow Bandit"
            PosQ = CFrame.new(1389.74451, 88.1519318, -1298.90796, -0.342042685, 0, 0.939684391, 0, 1, 0, -0.939684391, 0, -0.342042685)
            PosM = CFrame.new(1354.347900390625, 87.27277374267578, -1393.946533203125)
        elseif a == 100 or a <= 119 then
            Mon = "Snowman"
            Qdata = 2;
            Qname = "SnowQuest"
            NameMon = "Snowman"
            PosQ = CFrame.new(1389.74451, 88.1519318, -1298.90796, -0.342042685, 0, 0.939684391, 0, 1, 0, -0.939684391, 0, -0.342042685)
            PosM = CFrame.new(6241.9951171875, 51.522083282471, -1243.9771728516)
        elseif a == 120 or a <= 149 then
            Mon = "Chief Petty Officer"
            Qdata = 1;
            Qname = "MarineQuest2"
            NameMon = "Chief Petty Officer"
            PosQ = CFrame.new(-5039.58643, 27.3500385, 4324.68018, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-4881.23095703125, 22.65204429626465, 4273.75244140625)
        elseif a == 150 or a <= 174 then
            Mon = "Sky Bandit"
            Qdata = 1;
            Qname = "SkyQuest"
            NameMon = "Sky Bandit"
            PosQ = CFrame.new(-4839.53027, 716.368591, -2619.44165, 0.866007268, 0, 0.500031412, 0, 1, 0, -0.500031412, 0, 0.866007268)
            PosM = CFrame.new(-4953.20703125, 295.74420166015625, -2899.22900390625)
        elseif a == 175 or a <= 189 then
            Mon = "Dark Master"
            Qdata = 2;
            Qname = "SkyQuest"
            NameMon = "Dark Master"
            PosQ = CFrame.new(-4839.53027, 716.368591, -2619.44165, 0.866007268, 0, 0.500031412, 0, 1, 0, -0.500031412, 0, 0.866007268)
            PosM = CFrame.new(-5259.8447265625, 391.3976745605469, -2229.035400390625)
        elseif a == 190 or a <= 209 then
            Mon = "Prisoner"
            Qdata = 1;
            Qname = "PrisonerQuest"
            NameMon = "Prisoner"
            PosQ = CFrame.new(5308.93115, 1.65517521, 475.120514, -0.0894274712, -5.00292918e-09, -0.995993316, 1.60817859e-09, 1, -5.16744869e-09, 0.995993316, -2.06384709e-09, -0.0894274712)
            PosM = CFrame.new(5098.9736328125, -0.3204058110713959, 474.2373352050781)
        elseif a == 210 or a <= 249 then
            Mon = "Dangerous Prisoner"
            Qdata = 2;
            Qname = "PrisonerQuest"
            NameMon = "Dangerous Prisoner"
            PosQ = CFrame.new(5308.93115, 1.65517521, 475.120514, -0.0894274712, -5.00292918e-09, -0.995993316, 1.60817859e-09, 1, -5.16744869e-09, 0.995993316, -2.06384709e-09, -0.0894274712)
            PosM = CFrame.new(5654.5634765625, 15.633401870727539, 866.2991943359375)
        elseif a == 250 or a <= 274 then
            Mon = "Toga Warrior"
            Qdata = 1;
            Qname = "ColosseumQuest"
            NameMon = "Toga Warrior"
            PosQ = CFrame.new(-1580.04663, 6.35000277, -2986.47534, -0.515037298, 0, -0.857167721, 0, 1, 0, 0.857167721, 0, -0.515037298)
            PosM = CFrame.new(-1820.21484375, 51.68385696411133, -2740.6650390625)
        elseif a == 275 or a <= 299 then
            Mon = "Gladiator"
            Qdata = 2;
            Qname = "ColosseumQuest"
            NameMon = "Gladiator"
            PosQ = CFrame.new(-1580.04663, 6.35000277, -2986.47534, -0.515037298, 0, -0.857167721, 0, 1, 0, 0.857167721, 0, -0.515037298)
            PosM = CFrame.new(-1292.838134765625, 56.380882263183594, -3339.031494140625)
        elseif a == 300 or a <= 324 then
            Boubty = false;
            Mon = "Military Soldier"
            Qdata = 1;
            Qname = "MagmaQuest"
            NameMon = "Military Soldier"
            PosQ = CFrame.new(-5313.37012, 10.9500084, 8515.29395, -0.499959469, 0, 0.866048813, 0, 1, 0, -0.866048813, 0, -0.499959469)
            PosM = CFrame.new(-5411.16455078125, 11.081554412841797, 8454.29296875)
        elseif a == 325 or a <= 374 then
            Mon = "Military Spy"
            Qdata = 2;
            Qname = "MagmaQuest"
            NameMon = "Military Spy"
            PosQ = CFrame.new(-5313.37012, 10.9500084, 8515.29395, -0.499959469, 0, 0.866048813, 0, 1, 0, -0.866048813, 0, -0.499959469)
            PosM = CFrame.new(-5802.8681640625, 86.26241302490234, 8828.859375)
        elseif a == 375 or a <= 399 then
            Mon = "Fishman Warrior"
            Qdata = 1;
            Qname = "FishmanQuest"
            NameMon = "Fishman Warrior"
            PosQ = CFrame.new(61122.65234375, 18.497442245483, 1569.3997802734)
            PosM = CFrame.new(60878.30078125, 18.482830047607422, 1543.7574462890625)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 10000 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(61163.8515625, 11.6796875, 1819.7841796875))
            end
        elseif a == 400 or a <= 449 then
            Mon = "Fishman Commando"
            Qdata = 2;
            Qname = "FishmanQuest"
            NameMon = "Fishman Commando"
            PosQ = CFrame.new(61122.65234375, 18.497442245483, 1569.3997802734)
            PosM = CFrame.new(61922.6328125, 18.482830047607422, 1493.934326171875)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 10000 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(61163.8515625, 11.6796875, 1819.7841796875))
            end
        elseif a == 450 or a <= 474 then
            Mon = "God's Guard"
            Qdata = 1;
            Qname = "SkyExp1Quest"
            NameMon = "God's Guard"
            PosQ = CFrame.new(-4721.88867, 843.874695, -1949.96643, 0.996191859, -0, -0.0871884301, 0, 1, -0, 0.0871884301, 0, 0.996191859)
            PosM = CFrame.new(-4710.04296875, 845.2769775390625, -1927.3079833984375)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 10000 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(-4607.82275, 872.54248, -1667.55688))
            end
        elseif a == 475 or a <= 524 then
            Mon = "Shanda"
            Qdata = 2;
            Qname = "SkyExp1Quest"
            NameMon = "Shanda"
            PosQ = CFrame.new(-7859.09814, 5544.19043, -381.476196, -0.422592998, 0, 0.906319618, 0, 1, 0, -0.906319618, 0, -0.422592998)
            PosM = CFrame.new(-7678.48974609375, 5566.40380859375, -497.2156066894531)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 10000 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(-7894.6176757813, 5547.1416015625, -380.29119873047))
            end
        elseif a == 525 or a <= 549 then
            Mon = "Royal Squad"
            Qdata = 1;
            Qname = "SkyExp2Quest"
            NameMon = "Royal Squad"
            PosQ = CFrame.new(-7906.81592, 5634.6626, -1411.99194, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-7624.25244140625, 5658.13330078125, -1467.354248046875)
        elseif a == 550 or a <= 624 then
            Mon = "Royal Soldier"
            Qdata = 2;
            Qname = "SkyExp2Quest"
            NameMon = "Royal Soldier"
            PosQ = CFrame.new(-7906.81592, 5634.6626, -1411.99194, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-7836.75341796875, 5645.6640625, -1790.6236572265625)
        elseif a == 625 or a <= 649 then
            Mon = "Galley Pirate"
            Qdata = 1;
            Qname = "FountainQuest"
            NameMon = "Galley Pirate"
            PosQ = CFrame.new(5259.81982, 37.3500175, 4050.0293, 0.087131381, 0, 0.996196866, 0, 1, 0, -0.996196866, 0, 0.087131381)
            PosM = CFrame.new(5551.02197265625, 78.90135192871094, 3930.412841796875)
        elseif a >= 650 then
            Mon = "Galley Captain"
            Qdata = 2;
            Qname = "FountainQuest"
            NameMon = "Galley Captain"
            PosQ = CFrame.new(5259.81982, 37.3500175, 4050.0293, 0.087131381, 0, 0.996196866, 0, 1, 0, -0.996196866, 0, 0.087131381)
            PosM = CFrame.new(5441.95166015625, 42.50205993652344, 4950.09375)
        end
    elseif World2 then
        if a == 700 or a <= 724 then
            Mon = "Raider"
            Qdata = 1;
            Qname = "Area1Quest"
            NameMon = "Raider"
            PosQ = CFrame.new(-429.543518, 71.7699966, 1836.18188, -0.22495985, 0, -0.974368095, 0, 1, 0, 0.974368095, 0, -0.22495985)
            PosM = CFrame.new(-728.3267211914062, 52.779319763183594, 2345.7705078125)
        elseif a == 725 or a <= 774 then
            Mon = "Mercenary"
            Qdata = 2;
            Qname = "Area1Quest"
            NameMon = "Mercenary"
            PosQ = CFrame.new(-429.543518, 71.7699966, 1836.18188, -0.22495985, 0, -0.974368095, 0, 1, 0, 0.974368095, 0, -0.22495985)
            PosM = CFrame.new(-1004.3244018554688, 80.15886688232422, 1424.619384765625)
        elseif a == 775 or a <= 799 then
            Mon = "Swan Pirate"
            Qdata = 1;
            Qname = "Area2Quest"
            NameMon = "Swan Pirate"
            PosQ = CFrame.new(638.43811, 71.769989, 918.282898, 0.139203906, 0, 0.99026376, 0, 1, 0, -0.99026376, 0, 0.139203906)
            PosM = CFrame.new(1068.664306640625, 137.61428833007812, 1322.1060791015625)
        elseif a == 800 or a <= 874 then
            Mon = "Factory Staff"
            Qname = "Area2Quest"
            Qdata = 2;
            NameMon = "Factory Staff"
            PosQ = CFrame.new(632.698608, 73.1055908, 918.666321, -0.0319722369, 8.96074881e-10, -0.999488771, 1.36326533e-10, 1, 8.92172336e-10, 0.999488771, -1.07732087e-10, -0.0319722369)
            PosM = CFrame.new(73.07867431640625, 81.86344146728516, -27.470672607421875)
        elseif a == 875 or a <= 899 then
            Mon = "Marine Lieutenant"
            Qdata = 1;
            Qname = "MarineQuest3"
            NameMon = "Marine Lieutenant"
            PosQ = CFrame.new(-2440.79639, 71.7140732, -3216.06812, 0.866007268, 0, 0.500031412, 0, 1, 0, -0.500031412, 0, 0.866007268)
            PosM = CFrame.new(-2821.372314453125, 75.89727783203125, -3070.089111328125)
        elseif a == 900 or a <= 949 then
            Mon = "Marine Captain"
            Qdata = 2;
            Qname = "MarineQuest3"
            NameMon = "Marine Captain"
            PosQ = CFrame.new(-2440.79639, 71.7140732, -3216.06812, 0.866007268, 0, 0.500031412, 0, 1, 0, -0.500031412, 0, 0.866007268)
            PosM = CFrame.new(-1861.2310791015625, 80.17658233642578, -3254.697509765625)
        elseif a == 950 or a <= 974 then
            Mon = "Zombie"
            Qdata = 1;
            Qname = "ZombieQuest"
            NameMon = "Zombie"
            PosQ = CFrame.new(-5497.06152, 47.5923004, -795.237061, -0.29242146, 0, -0.95628953, 0, 1, 0, 0.95628953, 0, -0.29242146)
            PosM = CFrame.new(-5657.77685546875, 78.96973419189453, -928.68701171875)
        elseif a == 975 or a <= 999 then
            Mon = "Vampire"
            Qdata = 2;
            Qname = "ZombieQuest"
            NameMon = "Vampire"
            PosQ = CFrame.new(-5497.06152, 47.5923004, -795.237061, -0.29242146, 0, -0.95628953, 0, 1, 0, 0.95628953, 0, -0.29242146)
            PosM = CFrame.new(-6037.66796875, 32.18463897705078, -1340.6597900390625)
        elseif a == 1000 or a <= 1049 then
            Mon = "Snow Trooper"
            Qdata = 1;
            Qname = "SnowMountainQuest"
            NameMon = "Snow Trooper"
            PosQ = CFrame.new(609.858826, 400.119904, -5372.25928, -0.374604106, 0, 0.92718488, 0, 1, 0, -0.92718488, 0, -0.374604106)
            PosM = CFrame.new(549.1473388671875, 427.3870544433594, -5563.69873046875)
        elseif a == 1050 or a <= 1099 then
            Mon = "Winter Warrior"
            Qdata = 2;
            Qname = "SnowMountainQuest"
            NameMon = "Winter Warrior"
            PosQ = CFrame.new(609.858826, 400.119904, -5372.25928, -0.374604106, 0, 0.92718488, 0, 1, 0, -0.92718488, 0, -0.374604106)
            PosM = CFrame.new(1142.7451171875, 475.6398010253906, -5199.41650390625)
        elseif a == 1100 or a <= 1124 then
            Mon = "Lab Subordinate"
            Qdata = 1;
            Qname = "IceSideQuest"
            NameMon = "Lab Subordinate"
            PosQ = CFrame.new(-6064.06885, 15.2422857, -4902.97852, 0.453972578, -0, -0.891015649, 0, 1, -0, 0.891015649, 0, 0.453972578)
            PosM = CFrame.new(-5707.4716796875, 15.951709747314453, -4513.39208984375)
        elseif a == 1125 or a <= 1174 then
            Mon = "Horned Warrior"
            Qdata = 2;
            Qname = "IceSideQuest"
            NameMon = "Horned Warrior"
            PosQ = CFrame.new(-6064.06885, 15.2422857, -4902.97852, 0.453972578, -0, -0.891015649, 0, 1, -0, 0.891015649, 0, 0.453972578)
            PosM = CFrame.new(-6341.36669921875, 15.951770782470703, -5723.162109375)
        elseif a == 1175 or a <= 1199 then
            Mon = "Magma Ninja"
            Qdata = 1;
            Qname = "FireSideQuest"
            NameMon = "Magma Ninja"
            PosQ = CFrame.new(-5428.03174, 15.0622921, -5299.43457, -0.882952213, 0, 0.469463557, 0, 1, 0, -0.469463557, 0, -0.882952213)
            PosM = CFrame.new(-5449.6728515625, 76.65874481201172, -5808.20068359375)
        elseif a == 1200 or a <= 1249 then
            Mon = "Lava Pirate"
            Qdata = 2;
            Qname = "FireSideQuest"
            NameMon = "Lava Pirate"
            PosQ = CFrame.new(-5428.03174, 15.0622921, -5299.43457, -0.882952213, 0, 0.469463557, 0, 1, 0, -0.469463557, 0, -0.882952213)
            PosM = CFrame.new(-5213.33154296875, 49.73788070678711, -4701.451171875)
        elseif a == 1250 or a <= 1274 then
            Mon = "Ship Deckhand"
            Qdata = 1;
            Qname = "ShipQuest1"
            NameMon = "Ship Deckhand"
            PosQ = CFrame.new(1037.80127, 125.092171, 32911.6016)
            PosM = CFrame.new(1212.0111083984375, 150.79205322265625, 33059.24609375)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 500 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(923.21252441406, 126.9760055542, 32852.83203125))
            end
        elseif a == 1275 or a <= 1299 then
            Mon = "Ship Engineer"
            Qdata = 2;
            Qname = "ShipQuest1"
            NameMon = "Ship Engineer"
            PosQ = CFrame.new(1037.80127, 125.092171, 32911.6016)
            PosM = CFrame.new(919.4786376953125, 43.54401397705078, 32779.96875)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 500 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(923.21252441406, 126.9760055542, 32852.83203125))
            end
        elseif a == 1300 or a <= 1324 then
            Mon = "Ship Steward"
            Qdata = 1;
            Qname = "ShipQuest2"
            NameMon = "Ship Steward"
            PosQ = CFrame.new(968.80957, 125.092171, 33244.125)
            PosM = CFrame.new(919.4385375976562, 129.55599975585938, 33436.03515625)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 500 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(923.21252441406, 126.9760055542, 32852.83203125))
            end
        elseif a == 1325 or a <= 1349 then
            Mon = "Ship Officer"
            Qdata = 2;
            Qname = "ShipQuest2"
            NameMon = "Ship Officer"
            PosQ = CFrame.new(968.80957, 125.092171, 33244.125)
            PosM = CFrame.new(1036.0179443359375, 181.4390411376953, 33315.7265625)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 500 then
                replicated.Remotes.CommF_:InvokeServer("requestEntrance", Vector3.new(923.21252441406, 126.9760055542, 32852.83203125))
            end
        elseif a == 1350 or a <= 1374 then
            Mon = "Arctic Warrior"
            Qdata = 1;
            Qname = "FrostQuest"
            NameMon = "Arctic Warrior"
            PosQ = CFrame.new(5667.6582, 26.7997818, -6486.08984, -0.933587909, 0, -0.358349502, 0, 1, 0, 0.358349502, 0, -0.933587909)
            PosM = CFrame.new(5966.24609375, 62.97002029418945, -6179.3828125)
            if _G.Level and (PosQ.Position - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude > 1000 then
                BTP(PosM)
            end
        elseif a == 1375 or a <= 1424 then
            Mon = "Snow Lurker"
            Qdata = 2;
            Qname = "FrostQuest"
            NameMon = "Snow Lurker"
            PosQ = CFrame.new(5667.6582, 26.7997818, -6486.08984, -0.933587909, 0, -0.358349502, 0, 1, 0, 0.358349502, 0, -0.933587909)
            PosM = CFrame.new(5407.07373046875, 69.19437408447266, -6880.88037109375)
        elseif a == 1425 or a <= 1449 then
            Mon = "Sea Soldier"
            Qdata = 1;
            Qname = "ForgottenQuest"
            NameMon = "Sea Soldier"
            PosQ = CFrame.new(-3054.44458, 235.544281, -10142.8193, 0.990270376, -0, -0.13915664, 0, 1, -0, 0.13915664, 0, 0.990270376)
            PosM = CFrame.new(-3028.2236328125, 64.67451477050781, -9775.4267578125)
        elseif a >= 1450 then
            Mon = "Water Fighter"
            Qdata = 2;
            Qname = "ForgottenQuest"
            NameMon = "Water Fighter"
            PosQ = CFrame.new(-3054.44458, 235.544281, -10142.8193, 0.990270376, -0, -0.13915664, 0, 1, -0, 0.13915664, 0, 0.990270376)
            PosM = CFrame.new(-3352.9013671875, 285.01556396484375, -10534.841796875)
        end
    elseif World3 then
        if a == 1500 or a <= 1524 then
            Mon = "Pirate Millionaire"
            Qdata = 1;
            Qname = "PiratePortQuest"
            NameMon = "Pirate Millionaire"
            PosQ = CFrame.new(-712.8272705078125, 98.5770492553711, 5711.9541015625)
            PosM = CFrame.new(-712.8272705078125, 98.5770492553711, 5711.9541015625)
        elseif a == 1525 or a <= 1574 then
            Mon = "Pistol Billionaire"
            Qdata = 2;
            Qname = "PiratePortQuest"
            NameMon = "Pistol Billionaire"
            PosQ = CFrame.new(-723.4331665039062, 147.42906188964844, 5931.9931640625)
            PosM = CFrame.new(-723.4331665039062, 147.42906188964844, 5931.9931640625)
        elseif a == 1575 or a <= 1599 then
            Mon = "Dragon Crew Warrior"
            Qdata = 1;
            Qname = "AmazonQuest"
            NameMon = "Dragon Crew Warrior"
            PosQ = CFrame.new(6779.03271484375, 111.16865539550781, -801.2130737304688)
            PosM = CFrame.new(6779.03271484375, 111.16865539550781, -801.2130737304688)
        elseif a == 1600 or a <= 1624 then
            Mon = "Dragon Crew Archer"
            Qname = "AmazonQuest"
            Qdata = 2;
            NameMon = "Dragon Crew Archer"
            PosQ = CFrame.new(6955.8974609375, 546.6658935546875, 309.0401306152344)
            PosM = CFrame.new(6955.8974609375, 546.6658935546875, 309.0401306152344)
        elseif a == 1625 or a <= 1649 then
            Mon = "Hydra Enforcer"
            Qname = "VenomCrewQuest"
            Qdata = 1;
            NameMon = "Hydra Enforcer"
            PosQ = CFrame.new(4620.61572265625, 1002.2954711914062, 399.0868835449219)
            PosM = CFrame.new(4620.61572265625, 1002.2954711914062, 399.0868835449219)
        elseif a == 1650 or a <= 1699 then
            Mon = "Venomous Assailant"
            Qname = "VenomCrewQuest"
            Qdata = 2;
            NameMon = "Venomous Assailant"
            PosQ = CFrame.new(4697.5918, 1100.65137, 946.401978, 0.579397917, -4.19689783e-10, 0.81504482, -1.49287818e-10, 1, 6.21053986e-10, -0.81504482, -4.81513662e-10, 0.579397917)
            PosM = CFrame.new(4697.5918, 1100.65137, 946.401978, 0.579397917, -4.19689783e-10, 0.81504482, -1.49287818e-10, 1, 6.21053986e-10, -0.81504482, -4.81513662e-10, 0.579397917)
        elseif a == 1700 or a <= 1724 then
            Mon = "Marine Commodore"
            Qdata = 1;
            Qname = "MarineTreeIsland"
            NameMon = "Marine Commodore"
            PosQ = CFrame.new(2180.54126, 27.8156815, -6741.5498, -0.965929747, 0, 0.258804798, 0, 1, 0, -0.258804798, 0, -0.965929747)
            PosM = CFrame.new(2286.0078125, 73.13391876220703, -7159.80908203125)
        elseif a == 1725 or a <= 1774 then
            Mon = "Marine Rear Admiral"
            NameMon = "Marine Rear Admiral"
            Qname = "MarineTreeIsland"
            Qdata = 2;
            PosQ = CFrame.new(2179.98828125, 28.731239318848, -6740.0551757813)
            PosM = CFrame.new(3656.773681640625, 160.52406311035156, -7001.5986328125)
        elseif a == 1775 or a <= 1799 then
            Mon = "Fishman Raider"
            Qdata = 1;
            Qname = "DeepForestIsland3"
            NameMon = "Fishman Raider"
            PosQ = CFrame.new(-10581.6563, 330.872955, -8761.18652, -0.882952213, 0, 0.469463557, 0, 1, 0, -0.469463557, 0, -0.882952213)
            PosM = CFrame.new(-10407.5263671875, 331.76263427734375, -8368.5166015625)
        elseif a == 1800 or a <= 1824 then
            Mon = "Fishman Captain"
            Qdata = 2;
            Qname = "DeepForestIsland3"
            NameMon = "Fishman Captain"
            PosQ = CFrame.new(-10581.6563, 330.872955, -8761.18652, -0.882952213, 0, 0.469463557, 0, 1, 0, -0.469463557, 0, -0.882952213)
            PosM = CFrame.new(-10994.701171875, 352.38140869140625, -9002.1103515625)
        elseif a == 1825 or a <= 1849 then
            Mon = "Forest Pirate"
            Qdata = 1;
            Qname = "DeepForestIsland"
            NameMon = "Forest Pirate"
            PosQ = CFrame.new(-13234.04, 331.488495, -7625.40137, 0.707134247, -0, -0.707079291, 0, 1, -0, 0.707079291, 0, 0.707134247)
            PosM = CFrame.new(-13274.478515625, 332.3781433105469, -7769.58056640625)
        elseif a == 1850 or a <= 1899 then
            Mon = "Mythological Pirate"
            Qdata = 2;
            Qname = "DeepForestIsland"
            NameMon = "Mythological Pirate"
            PosQ = CFrame.new(-13234.04, 331.488495, -7625.40137, 0.707134247, -0, -0.707079291, 0, 1, -0, 0.707079291, 0, 0.707134247)
            PosM = CFrame.new(-13680.607421875, 501.08154296875, -6991.189453125)
        elseif a == 1900 or a <= 1924 then
            Mon = "Jungle Pirate"
            Qdata = 1;
            Qname = "DeepForestIsland2"
            NameMon = "Jungle Pirate"
            PosQ = CFrame.new(-12680.3818, 389.971039, -9902.01953, -0.0871315002, 0, 0.996196866, 0, 1, 0, -0.996196866, 0, -0.0871315002)
            PosM = CFrame.new(-12256.16015625, 331.73828125, -10485.8369140625)
        elseif a == 1925 or a <= 1974 then
            Mon = "Musketeer Pirate"
            Qdata = 2;
            Qname = "DeepForestIsland2"
            NameMon = "Musketeer Pirate"
            PosQ = CFrame.new(-12680.3818, 389.971039, -9902.01953, -0.0871315002, 0, 0.996196866, 0, 1, 0, -0.996196866, 0, -0.0871315002)
            PosM = CFrame.new(-13457.904296875, 391.545654296875, -9859.177734375)
        elseif a == 1975 or a <= 1999 then
            Mon = "Reborn Skeleton"
            Qdata = 1;
            Qname = "HauntedQuest1"
            NameMon = "Reborn Skeleton"
            PosQ = CFrame.new(-9479.2168, 141.215088, 5566.09277, 0, 0, 1, 0, 1, -0, -1, 0, 0)
            PosM = CFrame.new(-8763.7236328125, 165.72299194335938, 6159.86181640625)
        elseif a == 2000 or a <= 2024 then
            Mon = "Living Zombie"
            Qdata = 2;
            Qname = "HauntedQuest1"
            NameMon = "Living Zombie"
            PosQ = CFrame.new(-9479.2168, 141.215088, 5566.09277, 0, 0, 1, 0, 1, -0, -1, 0, 0)
            PosM = CFrame.new(-10144.1318359375, 138.62667846679688, 5838.0888671875)
        elseif a == 2025 or a <= 2049 then
            Mon = "Demonic Soul"
            Qdata = 1;
            Qname = "HauntedQuest2"
            NameMon = "Demonic Soul"
            PosQ = CFrame.new(-9516.99316, 172.017181, 6078.46533, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-9505.8720703125, 172.10482788085938, 6158.9931640625)
        elseif a == 2050 or a <= 2074 then
            Mon = "Posessed Mummy"
            Qdata = 2;
            Qname = "HauntedQuest2"
            NameMon = "Posessed Mummy"
            PosQ = CFrame.new(-9516.99316, 172.017181, 6078.46533, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-9582.0224609375, 6.251527309417725, 6205.478515625)
        elseif a == 2075 or a <= 2099 then
            Mon = "Peanut Scout"
            Qdata = 1;
            Qname = "NutsIslandQuest"
            NameMon = "Peanut Scout"
            PosQ = CFrame.new(-2104.3908691406, 38.104167938232, -10194.21875, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-2143.241943359375, 47.72198486328125, -10029.9951171875)
        elseif a == 2100 or a <= 2124 then
            Mon = "Peanut President"
            Qdata = 2;
            Qname = "NutsIslandQuest"
            NameMon = "Peanut President"
            PosQ = CFrame.new(-2104.3908691406, 38.104167938232, -10194.21875, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-1859.35400390625, 38.10316848754883, -10422.4296875)
        elseif a == 2125 or a <= 2149 then
            Mon = "Ice Cream Chef"
            Qdata = 1;
            Qname = "IceCreamIslandQuest"
            NameMon = "Ice Cream Chef"
            PosQ = CFrame.new(-820.64825439453, 65.819526672363, -10965.795898438, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-872.24658203125, 65.81957244873047, -10919.95703125)
        elseif a == 2150 or a <= 2199 then
            Mon = "Ice Cream Commander"
            Qdata = 2;
            Qname = "IceCreamIslandQuest"
            NameMon = "Ice Cream Commander"
            PosQ = CFrame.new(-820.64825439453, 65.819526672363, -10965.795898438, 0, 0, -1, 0, 1, 0, 1, 0, 0)
            PosM = CFrame.new(-558.06103515625, 112.04895782470703, -11290.7744140625)
        elseif a == 2200 or a <= 2224 then
            Mon = "Cookie Crafter"
            Qdata = 1;
            Qname = "CakeQuest1"
            NameMon = "Cookie Crafter"
            PosQ = CFrame.new(-2021.32007, 37.7982254, -12028.7295, 0.957576931, -8.80302053e-08, 0.288177818, 6.9301187e-08, 1, 7.51931211e-08, -0.288177818, -5.2032135e-08, 0.957576931)
            PosM = CFrame.new(-2374.13671875, 37.79826354980469, -12125.30859375)
        elseif a == 2225 or a <= 2249 then
            Mon = "Cake Guard"
            Qdata = 2;
            Qname = "CakeQuest1"
            NameMon = "Cake Guard"
            PosQ = CFrame.new(-2021.32007, 37.7982254, -12028.7295, 0.957576931, -8.80302053e-08, 0.288177818, 6.9301187e-08, 1, 7.51931211e-08, -0.288177818, -5.2032135e-08, 0.957576931)
            PosM = CFrame.new(-1598.3070068359375, 43.773197174072266, -12244.5810546875)
        elseif a == 2250 or a <= 2274 then
            Mon = "Baking Staff"
            Qdata = 1;
            Qname = "CakeQuest2"
            NameMon = "Baking Staff"
            PosQ = CFrame.new(-1927.91602, 37.7981339, -12842.5391, -0.96804446, 4.22142143e-08, 0.250778586, 4.74911062e-08, 1, 1.49904711e-08, -0.250778586, 2.64211941e-08, -0.96804446)
            PosM = CFrame.new(-1887.8099365234375, 77.6185073852539, -12998.3505859375)
        elseif a == 2275 or a <= 2299 then
            Mon = "Head Baker"
            Qdata = 2;
            Qname = "CakeQuest2"
            NameMon = "Head Baker"
            PosQ = CFrame.new(-1927.91602, 37.7981339, -12842.5391, -0.96804446, 4.22142143e-08, 0.250778586, 4.74911062e-08, 1, 1.49904711e-08, -0.250778586, 2.64211941e-08, -0.96804446)
            PosM = CFrame.new(-2216.188232421875, 82.884521484375, -12869.2939453125)
        elseif a == 2300 or a <= 2324 then
            Mon = "Cocoa Warrior"
            Qdata = 1;
            Qname = "ChocQuest1"
            NameMon = "Cocoa Warrior"
            PosQ = CFrame.new(233.22836303710938, 29.876001358032227, -12201.2333984375)
            PosM = CFrame.new(-21.55328369140625, 80.57499694824219, -12352.3876953125)
        elseif a == 2325 or a <= 2349 then
            Mon = "Chocolate Bar Battler"
            Qdata = 2;
            Qname = "ChocQuest1"
            NameMon = "Chocolate Bar Battler"
            PosQ = CFrame.new(233.22836303710938, 29.876001358032227, -12201.2333984375)
            PosM = CFrame.new(582.590576171875, 77.18809509277344, -12463.162109375)
        elseif a == 2350 or a <= 2374 then
            Mon = "Sweet Thief"
            Qdata = 1;
            Qname = "ChocQuest2"
            NameMon = "Sweet Thief"
            PosQ = CFrame.new(150.5066375732422, 30.693693161010742, -12774.5029296875)
            PosM = CFrame.new(165.1884765625, 76.05885314941406, -12600.8369140625)
        elseif a == 2375 or a <= 2399 then
            Mon = "Candy Rebel"
            Qdata = 2;
            Qname = "ChocQuest2"
            NameMon = "Candy Rebel"
            PosQ = CFrame.new(150.5066375732422, 30.693693161010742, -12774.5029296875)
            PosM = CFrame.new(134.86563110351562, 77.2476806640625, -12876.5478515625)
        elseif a == 2400 or a <= 2449 then
            Mon = "Candy Pirate"
            Qdata = 1;
            Qname = "CandyQuest1"
            NameMon = "Candy Pirate"
            PosQ = CFrame.new(-1150.0400390625, 20.378934860229492, -14446.3349609375)
            PosM = CFrame.new(-1310.5003662109375, 26.016523361206055, -14562.404296875)
        elseif a == 2450 or a <= 2474 then
            Mon = "Isle Outlaw"
            Qdata = 1;
            Qname = "TikiQuest1"
            NameMon = "Isle Outlaw"
            PosQ = CFrame.new(-16548.8164, 55.6059914, -172.8125, 0.213092566, -0, -0.977032006, 0, 1, -0, 0.977032006, 0, 0.213092566)
            PosM = CFrame.new(-16479.900390625, 226.6117401123047, -300.3114318847656)
        elseif a == 2475 or a <= 2499 then
            Mon = "Island Boy"
            Qdata = 2;
            Qname = "TikiQuest1"
            NameMon = "Island Boy"
            PosQ = CFrame.new(-16548.8164, 55.6059914, -172.8125, 0.213092566, -0, -0.977032006, 0, 1, -0, 0.977032006, 0, 0.213092566)
            PosM = CFrame.new(-16849.396484375, 192.86505126953125, -150.7853240966797)
        elseif a == 2500 or a <= 2524 then
            Mon = "Sun-kissed Warrior"
            Qdata = 1;
            Qname = "TikiQuest2"
            NameMon = "kissed Warrior"
            PosM = CFrame.new(-16347, 64, 984)
            PosQ = CFrame.new(-16538, 55, 1049)
        elseif a == 2525 or a <= 2550 then
            Mon = "Isle Champion"
            Qdata = 2;
            Qname = "TikiQuest2"
            NameMon = "Isle Champion"
            PosQ = CFrame.new(-16541.0215, 57.3082275, 1051.46118, 0.0410757065, -0, -0.999156058, 0, 1, -0, 0.999156058, 0, 0.0410757065)
            PosM = CFrame.new(-16602.1015625, 130.38734436035156, 1087.24560546875)
        elseif a >= 2551 and a <= 2574 then
            Mon = "Serpent Hunter"
            Qdata = 1;
            Qname = "TikiQuest3";
            NameMon = "Serpent Hunter"
            PosQ = CFrame.new(-16679.4785, 176.7473, 1474.3995)
            PosM = CFrame.new(-16679.4785, 176.7473, 1474.3995)
        elseif a >= 2575 and a <= 2599 then
            Mon = "Skull Slayer"
            Qdata = 2;
            Qname = "TikiQuest3";
            NameMon = "Skull Slayer"
            PosQ = CFrame.new(-16759.5898, 71.2837, 1595.3399)
            PosM = CFrame.new(-16759.5898, 71.2837, 1595.3399)
        elseif a >= 2600 and a <= 2624 then
            Mon = "Reef Bandit"
            Qdata = 1;
            Qname = "SubmergedQuest1";
            NameMon = "Reef Bandit"
            PosQ = CFrame.new(10882.264, -2086.322, 10034.226)
            PosM = CFrame.new(10736.6191, -2087.8439, 9338.4882)
        elseif a >= 2625 and a <= 2649 then
            Mon = "Coral Pirate"
            Qdata = 2;
            Qname = "SubmergedQuest1";
            NameMon = "Coral Pirate"
            PosQ = CFrame.new(10882.264, -2086.322, 10034.226)
            PosM = CFrame.new(10965.1025, -2158.8842, 9177.2597)
        elseif a >= 2650 and a <= 2674 then
            Mon = "Sea Chanter"
            Qdata = 1;
            Qname = "SubmergedQuest2";
            NameMon = "Sea Chanter"
            PosQ = CFrame.new(10882.264, -2086.322, 10034.226)
            PosM = CFrame.new(10621.0342, -2087.8440, 10102.0332)
        elseif a >= 2675 and a <= 2699 then
            Mon = "Ocean Prophet"
            Qdata = 2;
            Qname = "SubmergedQuest2";
            NameMon = "Ocean Prophet"
            PosQ = CFrame.new(10882.264, -2086.322, 10034.226)
            PosM = CFrame.new(11056.1445, -2001.6717, 10117.4493)
        elseif a >= 2700 and a <= 2724 then
            Mon = "High Disciple"
            Qdata = 1;
            Qname = "SubmergedQuest3";
            NameMon = "High Disciple"
            PosQ = CFrame.new(9636.52441, -1992.19507, 9609.52832)
            PosM = CFrame.new(9828.087890625, -1940.908935546875, 9693.0634765625)
        elseif a >= 2725 and a <= 2800 then
            Mon = "Grand Devotee"
            Qdata = 2;
            Qname = "SubmergedQuest3";
            NameMon = "Grand Devotee"
            PosQ = CFrame.new(9636.52441, -1992.19507, 9609.52832)
            PosM = CFrame.new(9557.5849609375, -1928.0404052734375, 9859.1826171875)
        end
    end
end

-- FUNCTIONS

-- COMPONENTES
local v485 = v466:MakeTab({"Farming", "sword"})

local _ = v485:AddDropdown({
    Name = "Select Wepon",
    Description = "",
    Options = {"Melee", "Sword", "Gun", "Blox Fruit"},
    Default = "Melee",
    Flag = "WeaponType",
    Callback = function(v506)
        _G.SelectWeapon = v506
    end
})

local _ = v485:AddSection({"Main"})
v485:AddToggle({
    Name = "Auto Farm Level",
    Description = "",
    Default = false,
    Callback = function(v509)
        _G.AutoFarm = v509
        StopTween(_G.AutoFarm)
    end
})
spawn(function()
    while task.wait() do
        if _G.AutoFarm then
            pcall(function()
                local l_Text_0 = game:GetService("Players").LocalPlayer.PlayerGui.Main.Quest.Container.QuestTitle.Title.Text
                CheckQuest()
                if not string.find(l_Text_0, NameMon) then
                    StartBring = false
                    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("AbandonQuest")
                end
                if game:GetService("Players").LocalPlayer.PlayerGui.Main.Quest.Visible ~= false then
                    if game:GetService("Players").LocalPlayer.PlayerGui.Main.Quest.Visible == true then
                        if not string.find(l_Text_0, "kissed") then
                            if game:GetService("Workspace").Enemies:FindFirstChild(Mon) then
                                for _, v512 in pairs(game:GetService("Workspace").Enemies:GetChildren()) do
                                    if v512:FindFirstChild("HumanoidRootPart") and v512:FindFirstChild("Humanoid") and v512.Humanoid.Health > 0 and v512.Name == Mon then
                                        if not string.find(l_Text_0, NameMon) then
                                            StartBring = false
                                            game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("AbandonQuest")
                                        else
                                            repeat
                                                task.wait()
                                                EquipWeapon(_G.SelectWeapon)
                                                AutoHaki()
                                                PosMon = v512.HumanoidRootPart.CFrame
                                                topos(v512.HumanoidRootPart.CFrame * CFrame.new(0, 30, 0))
                                                v512.HumanoidRootPart.CanCollide = false
                                                v512.Humanoid.WalkSpeed = 0
                                                v512.Head.CanCollide = false
                                                v512.HumanoidRootPart.Size = Vector3.new(70, 70, 70)
                                                StartBring = true
                                                MonFarm = v512.Name
                                                game:GetService("VirtualUser"):CaptureController()
                                                game:GetService("VirtualUser"):Button1Down(Vector2.new(1280, 672))
                                            until not _G.AutoFarm or v512.Humanoid.Health <= 0 or not v512.Parent or game:GetService("Players").LocalPlayer.PlayerGui.Main.Quest.Visible == false
                                        end
                                    end
                                end
                            else
                                TP1(CFrameMon)
                                StartBring = false
                                if game:GetService("ReplicatedStorage"):FindFirstChild(Mon) then
                                    TP1(game:GetService("ReplicatedStorage"):FindFirstChild(Mon).HumanoidRootPart.CFrame * CFrame.new(0, 20, 0))
                                end
                            end
                        else
                            for _, v514 in pairs(game:GetService("Workspace").Enemies:GetChildren()) do
                                if string.find(v514.Name, "kissed Warrior") then
                                    if v514:FindFirstChild("HumanoidRootPart") and v514:FindFirstChild("Humanoid") and v514.Humanoid.Health > 0 then
                                        if string.find(l_Text_0, NameMon) then
                                            repeat
                                                task.wait()
                                                EquipWeapon(_G.SelectWeapon)
                                                PosMon = v514.HumanoidRootPart.CFrame
                                                topos(v514.HumanoidRootPart.CFrame * CFrame.new(0, 30, 0))
                                                v514.HumanoidRootPart.CanCollide = false
                                                v514.Humanoid.WalkSpeed = 0
                                                v514.Head.CanCollide = false
                                                v514.HumanoidRootPart.Size = Vector3.new(70, 70, 70)
                                                StartBring = true
                                                MonFarm = v514.Name
                                                game:GetService("VirtualUser"):CaptureController()
                                                game:GetService("VirtualUser"):Button1Down(Vector2.new(1280, 672))
                                            until not _G.AutoFarm or v514.Humanoid.Health <= 0 or not v514.Parent or game:GetService("Players").LocalPlayer.PlayerGui.Main.Quest.Visible == false
                                        else
                                            StartBring = false
                                            game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("AbandonQuest")
                                        end
                                    end
                                else
                                    TP1(CFrameMon)
                                    StartBring = false
                                    if game:GetService("ReplicatedStorage"):FindFirstChild(Mon) then
                                        TP1(game:GetService("ReplicatedStorage"):FindFirstChild(Mon).HumanoidRootPart.CFrame * CFrame.new(0, 20, 0))
                                    end
                                end
                            end
                        end
                    end
                else
                    StartBring = false
                    if BypassTP then
                        if (game.Players.LocalPlayer.Character.HumanoidRootPart.Position - CFrameQuest.Position).Magnitude <= 1500 then
                            TP1(CFrameQuest)
                        else
                            TP1(CFrameQuest)
                        end
                    else
                        TP1(CFrameQuest)
                    end
                    if (game.Players.LocalPlayer.Character.HumanoidRootPart.Position - CFrameQuest.Position).Magnitude <= 20 then
                        game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("StartQuest", NameQuest, LevelQuest)
                    end
                end
            end)
        end
    end
end)

-- COMPONENTES
